trigger:
- master

pool:
  name: Default


steps:

# Install Node
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: Install Node.js

# Install dependencies
- script: |
    npm install
  displayName: Install Dependencies


# Install JFrog CLI
- script: |
    curl -fL https://install-cli.jfrog.io | sh
    sudo mv jf /usr/local/bin/jf
  displayName: Install JFrog CLI

# Configure JFrog CLI
- script: |
    jf c add artifactory-server \
      --url=$(JF_URL) \
      --access-token=$(JF_ACCESS_TOKEN) \
      --interactive=false
  displayName: Configure JFrog CLI

# Configure npm with Artifactory
- script: |
    jf npm-config \
      --repo-resolve=$(NPM_REPO) \
      --repo-deploy=$(NPM_REPO)
  displayName: Configure npm for Artifactory


